/**:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.25
    max_hamming: 0
    detector:
      threads: 2
      decimate: 1.0
      blur: 0.0
      refine: true
      debug: false
