name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.rules/**'
      - 'LICENSE'
      - '.gitignore'
      - '**/*.pdf'
      - '**/*.gv'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.rules/**'
      - 'LICENSE'
      - '.gitignore'
      - '**/*.pdf'
      - '**/*.gv'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ros-tooling/setup-ros-docker/setup-ros-docker-ubuntu-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: >
            lunabot_bringup
            lunabot_control
            lunabot_description
            lunabot_localisation
            lunabot_navigation
            lunabot_perception
            lunabot_simulation
            lunabot_teleop
          target-ros2-distro: humble
